name: setup-veryl
description: Setup veryl on GitHub Actions runners
author: 'Naoya Hatta'
branding:
  color: green
  icon: download
inputs:
  version:
    description: Version of Veryl to install
    required: false
    default: latest
runs:
  using: node20
  main: dist/index.js
