name: Tests

on:
  push:
    branches:
    - master
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, ubuntu-20.04, macos-latest]
        version: [latest, 5.024]
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup verilator
      uses: ./
      with:
        version: ${{ matrix.version }}

    - name: Capture verilator version installed
      run: |
        verilator --version
        echo 'VERILATOR_VERSION_INSTALLED<<EOF' >> $GITHUB_ENV
        verilator --version >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV

    - name: Verify
      shell: python
      if: ${{ matrix.version != 'latest' }}
      env:
        VERILATOR_VERSION_EXPECTED: ${{ matrix.version }}
      run: |
        import sys, os
        sys.exit(
            int(not os.environ["VERILATOR_VERSION_EXPECTED"] in os.environ["VERILATOR_VERSION_INSTALLED"])
        )
